# version: '3.7'
services:
    app:
        build: .
        container_name: "ocha-app"
        volumes:
            - "./app/:/var/www/html"
            # - "./config/apache/httpd.conf:/etc/apache2/apache2.conf"
        privileged: true
        ports:
            - "80:80"
        depends_on:
            - postgres
        environment:
            - DOCKER_ENV=true
            - DATABASE_HOST=postgres
            - DATABASE_NAME=ocha_render
            - DATABASE_USER=ochauser
            - DATABASE_PASSWORD=ochapassword
    postgres:
        image: postgres:15
        container_name: ocha-postgres
        volumes:
            - ./config/postgres/data:/var/lib/postgresql/data
            - ./config/postgres/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
            - ./config/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
        environment:
            - POSTGRES_DB=ocha_render
            - POSTGRES_USER=ochauser
            - POSTGRES_PASSWORD=ochapassword
        ports:
            - "5432:5432"