databases:
  - name: ocha-mysql
    databaseName: ocha
    user: ochauser
    plan: free
    region: singapore
    Advanced:
      - key: MYSQL_DATABASE
      - key: MYSQL_USER
      - key: MYSQL_PASSWORD
      - key: MYSQL_ROOT_PASSWORD

services:
  - type: web
    name: ocha
    env: php
    region: singapore
    plan: free
    runtime: docker
    # buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ocha-mysql
          property: connectionString
      # - key: MYSQL_DATABASE
      # - key: MYSQL_USER
      # - key: MYSQL_PASSWORD
      # - key: MYSQL_ROOT_PASSWORD